<a href="https://colab.research.google.com/github/Deepanshusemwal10/ML-BASIC-/blob/main/MLlab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [ ]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [ ]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [ ]:
df['Age'] = df['Age'].fillna(value=df['Age'].mean())

In [ ]:
df.fillna(value='FILL VALUE')

       Age   Salary      Gender  Purchased
0    25.00  50000.0           M          0
1    30.00  60000.0           F          1
2   273.75  55000.0           F          0
3    40.00  70000.0           M          1
4  1000.00  70000.0  FILL VALUE          0

In [ ]:
df = pd.DataFrame({
    'Age': [25, 30, np.nan, 40, 1000, 25],
    'Salary': [50000, 60000, 55000, np.nan, 70000, 50000],
    'Gender': ['M', 'F', 'F', 'M', np.nan, 'M'],
    'Purchased': [0, 1, 0, 1, 0, 0]
})

In [ ]:
df.drop_duplicates(inplace=True)
df

      Age   Salary Gender  Purchased
0    25.0  50000.0      M          0
1    30.0  60000.0      F          1
2     NaN  55000.0      F          0
3    40.0      NaN      M          1
4  1000.0  70000.0    NaN          0

In [ ]:
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Salary'].fillna(df['Salary'].max(), inplace=True)

/tmp/ipython-input-3614125637.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)
/tmp/ipython-input-3614125637.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].max(), inplace=True)

In [ ]:
df

       Age   Salary Gender  Purchased
0    25.00  50000.0      M          0
1    30.00  60000.0      F          1
2   273.75  55000.0      F          0
3    40.00  70000.0      M          1
4  1000.00  70000.0    NaN          0

In [ ]:
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)

/tmp/ipython-input-3657246551.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)

In [ ]:
df

       Age   Salary Gender  Purchased
0    25.00  50000.0      M          0
1    30.00  60000.0      F          1
2   273.75  55000.0      F          0
3    40.00  70000.0      M          1
4  1000.00  70000.0      F          0

In [ ]:
df['Salary_log']= np.log(df['Salary' ])
df

       Age   Salary Gender  Purchased  Salary_log
0    25.00  50000.0      M          0   10.819778
1    30.00  60000.0      F          1   11.002100
2   273.75  55000.0      F          0   10.915088
3    40.00  70000.0      M          1   11.156251
4  1000.00  70000.0      F          0   11.156251

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(-1, 1))
df[['Age', 'Salary', 'Salary_log']] = scaler.fit_transform(df[['Age', 'Salary','Salary_log']])

df

        Age  Salary Gender  Purchased  Salary_log
0 -1.000000    -1.0      M          0   -1.000000
1 -0.989744     0.0      F          1    0.083724
2 -0.489744    -0.5      F          0   -0.433474
3 -0.969231     1.0      M          1    1.000000
4  1.000000     1.0      F          0    1.000000

In [ ]:
df['Purchased'].value_counts()

Purchased
0    3
1    2
Name: count, dtype: int64

In [ ]:
from imblearn.under_sampling import RandomUnderSampler

X = df.drop('Purchased', axis=1)
y = df['Purchased']

rus = RandomUnderSampler()
X_under, y_under = rus.fit_resample(X, y)
X_under

        Age  Salary Gender  Salary_log
2 -0.489744    -0.5      F   -0.433474
0 -1.000000    -1.0      M   -1.000000
1 -0.989744     0.0      F    0.083724
3 -0.969231     1.0      M    1.000000

In [ ]:
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTE
x=df.drop('Purchased',axis=1)
y=df['Purchased']
le=LabelEncoder()
x['Gender']=le.fit_transform(x['Gender'])
smote=SMOTE(k_neighbors=1 , random_state=42)
x_smote,y_smote=smote.fit_resample(x,y)

In [ ]:
x_smote

        Age    Salary  Gender  Salary_log
0 -1.000000 -1.000000       1   -1.000000
1 -0.989744  0.000000       0    0.083724
2 -0.489744 -0.500000       0   -0.433474
3 -0.969231  1.000000       1    1.000000
4  1.000000  1.000000       0    1.000000
5 -0.973404  0.796543       0    0.813577

In [ ]:
y_smote

0    0
1    1
2    0
3    1
4    0
5    1
Name: Purchased, dtype: int64